package org.micro.commerce.product.domain.event;

public enum EventType {

    PRODUCT_CREATION_REQUESTED,
    PRODUCT_CREATION_VALIDATED,
    PRODUCT_CREATION_VALIDATION_FAILED,
    PRODUCT_CREATED,
    PRODUCT_CREATION_FAILED

}
